name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: echo "Hello World!"
      - name: Print goodbye 
        run: echo "Done - bye!"
    run: |
     echo "First output"
     echo "Second output"
